services:
  db:
    image: postgres:15-alpine
    container_name: yas_db
    hostname: yas_db
    restart: no # unless-stopped
    environment:
      - POSTGRES_DB=yas_db
      - POSTGRES_USER=yas
      - POSTGRES_PASSWORD=64XQ3r4Xkf
    ports:
      - "5432:5432"
    volumes:
      - yas_db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M # On limite la RAM

volumes:
  yas_db_data:
